modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "redwiredoors"
version = "${file.jarVersion}"
displayName = "RedWire: Doors"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/redwire-doors"
logoFile = "logo.png"
authors = "UnhappyWithoutU"
description = "Additional mod for RedWire, adding animated Sliding Doors!"

[[dependencies.redwiredoors]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwiredoors]]
modId = "redwirecore"
mandatory = true
versionRange = "[1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwiredoors]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.1.31,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwiredoors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
