modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "redwirecore"
version = "${file.jarVersion}"
displayName = "RedWire: Core"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/redwire-core"
logoFile = "logo.png"
authors = "UnhappyWithoutU"
description = "Core mod for all RedWire forge modifications!"

[[dependencies.redwirecore]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwirecore]]
modId = "redwirelampsandlighting"
mandatory = false
versionRange = "[1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwirecore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
