modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "redwirealloys"
version = "${file.jarVersion}"
displayName = "RedWire: Alloys"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/redwire-alloys"
logoFile = "logo.png"
authors = "UnhappyWithoutU"
description = "Additional mod for RedWire, add the well known Alloy Wire!"

[[dependencies.redwirealloys]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwirealloys]]
modId = "redwirecore"
mandatory = true
versionRange = "[1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.redwirealloys]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
